apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secret
  namespace: task-manager
type: Opaque
stringData:
  JWT_SECRET: change-me-in-production
  DATABASE_URL: postgresql://postgres:postgres@postgres.default.svc.cluster.local:5432/task_manager?schema=public
